sudo: false
language: python
python:
  - 2.7
  - 3.3
  - 3.4

env:
  - READTHEDOCS=1
  - PYLINT=1

install:
  - source .ci/travis/retry.sh
  - retry .ci/travis/install.sh

script:
  - .ci/travis/script.sh
