environment:
  global:
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C C:\\project\\.ci\\appveyor\\run_with_compiler.cmd"

  matrix:
    - PYTHON: "C:\\Python26"
      PYTHON_VERSION: "2.6.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python26-x64"
      PYTHON_VERSION: "2.6.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python33-x64"
      PYTHON_VERSION: "3.3.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "64"

build: false  # Not a C# project, build stuff at the test step instead.
clone_folder: c:\\project

install:
  # Install some additional Python modules which will be required by
  # the tests.  These can't be installed as part of the setup.py due
  # to file locking issues.
  - "%PYTHON%\\Scripts\\pip.exe install setuptools coverage wheel --upgrade"

test_script:
  - ps: cd C:\\project
  - "%WITH_COMPILER% %PYTHON%\\Scripts\\coverage.exe run setup.py test"
  - "%PYTHON%\\Scripts\\coverage.exe report"

after_test:
  - "%WITH_COMPILER% %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*
