//
// This file contains constants which can be used either internally or
// by users of pywincffi.
//
// NOTE: The tests for this file, tests/test_core/test_cdefs/test_constants.py
//       depend on a constant's names to follow this format:
//           #define NAME ...
//

// Windows constants
#define MAX_PATH ...

// Global handle types
#define STD_INPUT_HANDLE ...
#define STD_OUTPUT_HANDLE ...
#define STD_ERROR_HANDLE ...

// Input constants to various process related functions
#define PROCESS_CREATE_PROCESS ...
#define PROCESS_CREATE_THREAD ...
#define PROCESS_DUP_HANDLE ...
#define PROCESS_QUERY_INFORMATION ...
#define PROCESS_QUERY_LIMITED_INFORMATION ...
#define PROCESS_SET_INFORMATION ...
#define PROCESS_SET_QUOTA ...
#define PROCESS_SUSPEND_RESUME ...
#define PROCESS_TERMINATE ...
#define PROCESS_VM_OPERATION ...
#define PROCESS_VM_READ ...
#define PROCESS_VM_WRITE ...
#define SYNCHRONIZE ...

// Input constants for pipe operations
#define PIPE_TYPE_MESSAGE ...
#define PIPE_READMODE_BYTE ...
#define PIPE_READMODE_MESSAGE ...
#define PIPE_WAIT ...
#define PIPE_NOWAIT ...

// Input constants for GetFinalPathNameByHandle
#define FILE_NAME_NORMALIZED ...
#define FILE_NAME_OPENED ...
#define VOLUME_NAME_DOS ...
#define VOLUME_NAME_GUID ...
#define VOLUME_NAME_NONE ...
#define VOLUME_NAME_NT ...

// Input constants for LockFile*()
#define LOCKFILE_EXCLUSIVE_LOCK ...
#define LOCKFILE_FAIL_IMMEDIATELY ...

// Errors
#define INVALID_HANDLE_VALUE ...
#define ERROR_ACCESS_DENIED ...
#define ERROR_INVALID_PARAMETER ...
#define ERROR_PATH_NOT_FOUND ...
#define ERROR_NOT_ENOUGH_MEMORY ...



